### ISSUE TITLE
Realizar reunión de capacitación sobre SIG

### ISSUE THREAD

**Issue by iaga** [lancis-apc/cdmx#9]
Capacitación para la compilación de fuentes de información: protocolos de ingreso de datos dropbox & Geonetwork

Lugar: lancis-apc
Horario: Lunes 04/11/2019, 12:00 a 14:00

**Comment by vichdzgeo** [comment]
Se realizo la capacitación a dos integrantes del equipo, Alondra Guerra y Felipe López en la creación de metadatos con la plataforma de geonetwork.
